-- =====================================================
-- Seed: WIT.ID Chart of Accounts — FULL 5-Layer + PSAK Attributes
-- Generated from the live Supabase `coa` table (tenant 00000000-0000-0000-0000-000000000001).
-- 170 accounts · all reporting/PSAK attributes populated (PSAK 1 statement mapping + PSAK 2 cash flow).
--
-- Two-pass, environment-portable load (ADR-8):
--   Pass 1 — INSERT all rows (parent_account_id resolved in pass 2).
--   Pass 2 — wire parent_account_id by matching child -> parent account_code.
--
-- Idempotent: clears the tenant's coa rows first (CASCADE clears dependent journal refs).
-- Review before running on shared data — this DELETEs all coa rows for the tenant.
-- =====================================================

BEGIN;

DELETE FROM public.coa WHERE tenant_id = '00000000-0000-0000-0000-000000000001';

-- == Pass 1: insert all 170 accounts =========================================
INSERT INTO public.coa (
  tenant_id, account_code, coa_full_code, segment_code, account_name, name_en,
  account_type, coa_layer, level, normal_balance, sort_order,
  enum_laporan_keuangan, enum_laporan_keuangan_category,
  cash_flow_category, enum_cf_section, enum_cf_line,
  direct_indirect_cost, enum_cost_category, tax_code,
  contra_account, is_working_capital, is_non_cash_item, is_budgeted,
  is_tax_deductible, is_restricted, is_trial_balance, is_taxation_report,
  required_sub_gl, is_washed_out_account, required_child, is_active
)
SELECT '00000000-0000-0000-0000-000000000001', t.* FROM (VALUES
  ('1', '1', '1', 'AKTIVA', NULL, 'asset', 'category', 1, 'debit', 1, 'BALANCE_SHEET', 'ASSET', 'not_applicable', 'EXCLUDED', NULL, NULL, NULL, NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('1-10000', '1-10000', '10000', 'Aktiva Lancar', NULL, 'asset', 'type', 2, 'debit', 1, 'BALANCE_SHEET', 'ASSET', 'operating', 'OPERATING', NULL, NULL, NULL, NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('1-10001', '1-10001', '10001', 'Kas', NULL, 'asset', 'sub_account', 3, 'debit', 1, 'BALANCE_SHEET', 'ASSET', 'not_applicable', 'EXCLUDED', NULL, NULL, NULL, NULL, false, true, false, false, true, false, true, false, false, false, false, true),
  ('1-10001-1', '1-10001-1', '1', 'Kas Kecil IDR', NULL, 'asset', 'general_ledger', 4, 'debit', 1, 'BALANCE_SHEET', 'ASSET', 'not_applicable', 'EXCLUDED', NULL, NULL, NULL, NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('1-10002', '1-10002', '10002', 'Bank', NULL, 'asset', 'sub_account', 3, 'debit', 2, 'BALANCE_SHEET', 'ASSET', 'not_applicable', 'EXCLUDED', NULL, NULL, NULL, NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('1-10002-1', '1-10002-1', '1', 'BCA Operational 008-044-9739 (Irfan Arsandi)', NULL, 'asset', 'general_ledger', 4, 'debit', 1, 'BALANCE_SHEET', 'ASSET', 'not_applicable', 'EXCLUDED', NULL, NULL, NULL, NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('1-10002-2', '1-10002-2', '2', 'BCA Development 008-323-4170 (Irfan Arsandi)', NULL, 'asset', 'general_ledger', 4, 'debit', 2, 'BALANCE_SHEET', 'ASSET', 'not_applicable', 'EXCLUDED', NULL, NULL, NULL, NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('1-10002-3', '1-10002-3', '3', 'Mandiri 132-00-2268-3131 (PT. WIT)', NULL, 'asset', 'general_ledger', 4, 'debit', 3, 'BALANCE_SHEET', 'ASSET', 'not_applicable', 'EXCLUDED', NULL, NULL, NULL, NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('1-10002-4', '1-10002-4', '4', 'Mandiri 1022 (PT. WIT RSHS)', NULL, 'asset', 'general_ledger', 4, 'debit', 4, 'BALANCE_SHEET', 'ASSET', 'not_applicable', 'EXCLUDED', NULL, NULL, NULL, NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('1-10002-5', '1-10002-5', '5', 'Mandiri 5591 (PT. WIT)', NULL, 'asset', 'general_ledger', 4, 'debit', 5, 'BALANCE_SHEET', 'ASSET', 'not_applicable', 'EXCLUDED', NULL, NULL, NULL, NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('1-10002-6', '1-10002-6', '6', 'BRI (CV. Warmup)', NULL, 'asset', 'general_ledger', 4, 'debit', 6, 'BALANCE_SHEET', 'ASSET', 'not_applicable', 'EXCLUDED', NULL, NULL, NULL, NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('1-10003', '1-10003', '10003', 'Deposito & Investasi JK Pendek', NULL, 'asset', 'sub_account', 3, 'debit', 3, 'BALANCE_SHEET', 'ASSET', 'not_applicable', 'EXCLUDED', NULL, NULL, NULL, NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('1-10003-1', '1-10003-1', '1', 'Deposito JK Pendek', NULL, 'asset', 'general_ledger', 4, 'debit', 1, 'BALANCE_SHEET', 'ASSET', 'not_applicable', 'EXCLUDED', NULL, NULL, NULL, NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('1-10100', '1-10100', '10100', 'Piutang Usaha', NULL, 'asset', 'sub_account', 3, 'debit', 4, 'BALANCE_SHEET', 'ASSET', 'operating', 'OPERATING', 'Perubahan piutang usaha', NULL, NULL, NULL, false, true, false, false, true, false, true, false, false, false, false, true),
  ('1-10100-1', '1-10100-1', '1', 'Piutang Usaha - Lokal', NULL, 'asset', 'general_ledger', 4, 'debit', 1, 'BALANCE_SHEET', 'ASSET', 'operating', 'OPERATING', 'Perubahan piutang usaha', NULL, NULL, NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('1-10100-2', '1-10100-2', '2', 'Piutang Usaha - Luar Negeri', NULL, 'asset', 'general_ledger', 4, 'debit', 2, 'BALANCE_SHEET', 'ASSET', 'operating', 'OPERATING', 'Perubahan piutang usaha', NULL, NULL, NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('1-10100-9', '1-10100-9', '9', 'Penyisihan Piutang Tak Tertagih', NULL, 'asset', 'general_ledger', 4, 'credit', 9, 'BALANCE_SHEET', 'ASSET', 'non_cash', 'OPERATING', 'Penyisihan kerugian piutang', NULL, NULL, NULL, true, false, false, false, true, false, true, false, false, false, false, true),
  ('1-10200', '1-10200', '10200', 'Piutang Lain-lain', NULL, 'asset', 'sub_account', 3, 'debit', 5, 'BALANCE_SHEET', 'ASSET', 'operating', 'OPERATING', 'Perubahan piutang lain-lain', NULL, NULL, NULL, false, true, false, false, true, false, true, false, false, false, false, true),
  ('1-10200-1', '1-10200-1', '1', 'Piutang Karyawan', NULL, 'asset', 'general_ledger', 4, 'debit', 1, 'BALANCE_SHEET', 'ASSET', 'operating', 'OPERATING', 'Perubahan piutang lain-lain', NULL, NULL, NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('1-10200-9', '1-10200-9', '9', 'Piutang Lain-lain', NULL, 'asset', 'general_ledger', 4, 'debit', 9, 'BALANCE_SHEET', 'ASSET', 'operating', 'OPERATING', 'Perubahan piutang lain-lain', NULL, NULL, NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('1-10300', '1-10300', '10300', 'Uang Muka & Biaya Dibayar Dimuka', NULL, 'asset', 'sub_account', 3, 'debit', 6, 'BALANCE_SHEET', 'ASSET', 'operating', 'OPERATING', 'Perubahan uang muka dan biaya dibayar dimuka', NULL, NULL, NULL, false, true, false, false, true, false, true, false, false, false, false, true),
  ('1-10300-1', '1-10300-1', '1', 'Biaya Dibayar Dimuka', NULL, 'asset', 'general_ledger', 4, 'debit', 1, 'BALANCE_SHEET', 'ASSET', 'operating', 'OPERATING', 'Perubahan biaya dibayar dimuka', NULL, NULL, NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('1-10300-2', '1-10300-2', '2', 'Uang Muka Vendor', NULL, 'asset', 'general_ledger', 4, 'debit', 2, 'BALANCE_SHEET', 'ASSET', 'operating', 'OPERATING', 'Perubahan uang muka', NULL, NULL, NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('1-10400', '1-10400', '10400', 'Pajak Dibayar Dimuka', NULL, 'asset', 'sub_account', 3, 'debit', 7, 'BALANCE_SHEET', 'ASSET', 'operating', 'OPERATING', 'Perubahan pajak dibayar dimuka', NULL, NULL, NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('1-10400-1', '1-10400-1', '1', 'PPN Masukan', NULL, 'asset', 'general_ledger', 4, 'debit', 1, 'BALANCE_SHEET', 'ASSET', 'operating', 'OPERATING', 'Perubahan pajak dibayar dimuka', NULL, NULL, NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('1-10400-2', '1-10400-2', '2', 'PPh 25 Dibayar Dimuka', NULL, 'asset', 'general_ledger', 4, 'debit', 2, 'BALANCE_SHEET', 'ASSET', 'operating', 'OPERATING', 'Perubahan pajak dibayar dimuka', NULL, NULL, NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('1-10400-3', '1-10400-3', '3', 'PPh 23 Dibayar Dimuka', NULL, 'asset', 'general_ledger', 4, 'debit', 3, 'BALANCE_SHEET', 'ASSET', 'operating', NULL, NULL, NULL, NULL, NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('1-20000', '1-20000', '20000', 'Aktiva Tidak Lancar', NULL, 'asset', 'type', 2, 'debit', 2, 'BALANCE_SHEET', 'ASSET', 'investing', 'INVESTING', NULL, NULL, NULL, NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('1-20001', '1-20001', '20001', 'Aset Tetap Berwujud', NULL, 'asset', 'sub_account', 3, 'debit', 1, 'BALANCE_SHEET', 'ASSET', 'investing', 'INVESTING', 'Perubahan aset tetap berwujud', NULL, NULL, NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('1-20001-1', '1-20001-1', '1', 'Peralatan & Komputer', NULL, 'asset', 'general_ledger', 4, 'debit', 1, 'BALANCE_SHEET', 'ASSET', 'investing', 'INVESTING', 'Pembelian/(penjualan) aset tetap', NULL, NULL, NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('1-20001-2', '1-20001-2', '2', 'Kendaraan', NULL, 'asset', 'general_ledger', 4, 'debit', 2, 'BALANCE_SHEET', 'ASSET', 'investing', 'INVESTING', 'Pembelian/(penjualan) aset tetap', NULL, NULL, NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('1-20001-3', '1-20001-3', '3', 'Inventaris Kantor', NULL, 'asset', 'general_ledger', 4, 'debit', 3, 'BALANCE_SHEET', 'ASSET', 'investing', 'INVESTING', 'Pembelian/(penjualan) aset tetap', NULL, NULL, NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('1-20001-9', '1-20001-9', '9', 'Akumulasi Penyusutan Aset Tetap', NULL, 'asset', 'general_ledger', 4, 'credit', 9, 'BALANCE_SHEET', 'ASSET', 'non_cash', 'EXCLUDED', 'Penyusutan aset tetap', NULL, NULL, NULL, true, false, false, false, true, false, true, false, false, false, false, true),
  ('1-20002', '1-20002', '20002', 'Aset Tak Berwujud', NULL, 'asset', 'sub_account', 3, 'debit', 2, 'BALANCE_SHEET', 'ASSET', 'investing', 'INVESTING', 'Perubahan aset tak berwujud', NULL, NULL, NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('1-20002-1', '1-20002-1', '1', 'Software & Lisensi', NULL, 'asset', 'general_ledger', 4, 'debit', 1, 'BALANCE_SHEET', 'ASSET', 'investing', 'INVESTING', 'Pembelian/(penjualan) perangkat lunak & lisensi', NULL, NULL, NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('1-20002-9', '1-20002-9', '9', 'Akumulasi Amortisasi', NULL, 'asset', 'general_ledger', 4, 'credit', 9, 'BALANCE_SHEET', 'ASSET', 'non_cash', 'EXCLUDED', 'Amortisasi aset tak berwujud', NULL, NULL, NULL, true, false, false, false, true, false, true, false, false, false, false, true),
  ('1-20003', '1-20003', '20003', 'Aset Lain-lain', NULL, 'asset', 'sub_account', 3, 'debit', 3, 'BALANCE_SHEET', 'ASSET', 'investing', 'INVESTING', 'Perubahan aset lain-lain', NULL, NULL, NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('1-20003-1', '1-20003-1', '1', 'Deposito Jaminan', NULL, 'asset', 'general_ledger', 4, 'debit', 1, 'BALANCE_SHEET', 'ASSET', 'investing', 'INVESTING', 'Perubahan deposito jaminan', NULL, NULL, NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('1-20003-2', '1-20003-2', '2', 'Aset Pajak Tangguhan', NULL, 'asset', 'general_ledger', 4, 'debit', 2, 'BALANCE_SHEET', 'ASSET', 'operating', 'OPERATING', 'Perubahan aset pajak tangguhan', NULL, NULL, NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('2', '2', '2', 'KEWAJIBAN', NULL, 'liability', 'category', 1, 'credit', 2, 'BALANCE_SHEET', 'LIABILITY', 'not_applicable', 'EXCLUDED', NULL, NULL, NULL, NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('2-10000', '2-10000', '10000', 'Kewajiban Lancar', NULL, 'liability', 'type', 2, 'credit', 1, 'BALANCE_SHEET', 'LIABILITY', 'operating', 'OPERATING', NULL, NULL, NULL, NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('2-10100', '2-10100', '10100', 'Hutang Usaha', NULL, 'liability', 'sub_account', 3, 'credit', 1, 'BALANCE_SHEET', 'LIABILITY', 'operating', 'OPERATING', 'Perubahan hutang usaha', NULL, NULL, NULL, false, true, false, false, true, false, true, false, false, false, false, true),
  ('2-10100-1', '2-10100-1', '1', 'Hutang Vendor', NULL, 'liability', 'general_ledger', 4, 'credit', 1, 'BALANCE_SHEET', 'LIABILITY', 'operating', 'OPERATING', 'Perubahan hutang usaha', NULL, NULL, NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('2-10100-2', '2-10100-2', '2', 'Hutang Partner', NULL, 'liability', 'general_ledger', 4, 'credit', 2, 'BALANCE_SHEET', 'LIABILITY', 'operating', 'OPERATING', 'Perubahan hutang usaha', NULL, NULL, NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('2-10200', '2-10200', '10200', 'Hutang Pajak', NULL, 'liability', 'sub_account', 3, 'credit', 2, 'BALANCE_SHEET', 'LIABILITY', 'operating', 'OPERATING', 'Perubahan hutang pajak', NULL, NULL, NULL, false, true, false, false, true, false, true, false, false, false, false, true),
  ('2-10200-1', '2-10200-1', '1', 'Hutang PPh 21', NULL, 'liability', 'general_ledger', 4, 'credit', 1, 'BALANCE_SHEET', 'LIABILITY', 'operating', 'OPERATING', 'Perubahan hutang pajak', NULL, NULL, NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('2-10200-2', '2-10200-2', '2', 'Hutang PPh 23', NULL, 'liability', 'general_ledger', 4, 'credit', 2, 'BALANCE_SHEET', 'LIABILITY', 'operating', 'OPERATING', 'Perubahan hutang pajak', NULL, NULL, NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('2-10200-3', '2-10200-3', '3', 'Hutang PPh 4(2)', NULL, 'liability', 'general_ledger', 4, 'credit', 3, 'BALANCE_SHEET', 'LIABILITY', 'operating', 'OPERATING', 'Perubahan hutang pajak', NULL, NULL, NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('2-10200-4', '2-10200-4', '4', 'Hutang PPN', NULL, 'liability', 'general_ledger', 4, 'credit', 4, 'BALANCE_SHEET', 'LIABILITY', 'operating', 'OPERATING', 'Perubahan hutang pajak', NULL, NULL, NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('2-10200-5', '2-10200-5', '5', 'Hutang PPh 25', NULL, 'liability', 'general_ledger', 4, 'credit', 5, 'BALANCE_SHEET', 'LIABILITY', 'operating', 'OPERATING', 'Perubahan hutang pajak', NULL, NULL, NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('2-10300', '2-10300', '10300', 'Hutang Gaji & Tunjangan', NULL, 'liability', 'sub_account', 3, 'credit', 3, 'BALANCE_SHEET', 'LIABILITY', 'operating', 'OPERATING', 'Perubahan hutang gaji dan tunjangan', NULL, NULL, NULL, false, true, false, false, true, false, true, false, false, false, false, true),
  ('2-10300-1', '2-10300-1', '1', 'Hutang Gaji', NULL, 'liability', 'general_ledger', 4, 'credit', 1, 'BALANCE_SHEET', 'LIABILITY', 'operating', 'OPERATING', 'Perubahan hutang gaji dan tunjangan', NULL, NULL, NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('2-10300-2', '2-10300-2', '2', 'Hutang THR Akrual', NULL, 'liability', 'general_ledger', 4, 'credit', 2, 'BALANCE_SHEET', 'LIABILITY', 'operating', 'OPERATING', 'Perubahan hutang gaji dan tunjangan', NULL, NULL, NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('2-10400', '2-10400', '10400', 'Pendapatan Diterima Dimuka', NULL, 'liability', 'sub_account', 3, 'credit', 4, 'BALANCE_SHEET', 'LIABILITY', 'operating', 'OPERATING', 'Perubahan pendapatan diterima dimuka', NULL, NULL, NULL, false, true, false, false, true, false, true, false, false, false, false, true),
  ('2-10400-1', '2-10400-1', '1', 'DP Project Belum Diakui', NULL, 'liability', 'general_ledger', 4, 'credit', 1, 'BALANCE_SHEET', 'LIABILITY', 'operating', 'OPERATING', 'Perubahan pendapatan diterima dimuka', NULL, NULL, NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('2-10500', '2-10500', '10500', 'Biaya Masih Harus Dibayar', NULL, 'liability', 'sub_account', 3, 'credit', 5, 'BALANCE_SHEET', 'LIABILITY', 'operating', 'OPERATING', 'Perubahan biaya masih harus dibayar', NULL, NULL, NULL, false, true, false, false, true, false, true, false, false, false, false, true),
  ('2-10500-1', '2-10500-1', '1', 'Biaya Masih Harus Dibayar', NULL, 'liability', 'general_ledger', 4, 'credit', 1, 'BALANCE_SHEET', 'LIABILITY', 'operating', 'OPERATING', 'Perubahan biaya masih harus dibayar', NULL, NULL, NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('2-20000', '2-20000', '20000', 'Kewajiban Jangka Panjang', NULL, 'liability', 'type', 2, 'credit', 2, 'BALANCE_SHEET', 'LIABILITY', 'financing', 'FINANCING', NULL, NULL, NULL, NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('2-20100', '2-20100', '20100', 'Hutang Bank JK Panjang', NULL, 'liability', 'sub_account', 3, 'credit', 1, 'BALANCE_SHEET', 'LIABILITY', 'financing', 'FINANCING', 'Penerimaan/(pelunasan) hutang bank jangka panjang', NULL, NULL, NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('2-20100-1', '2-20100-1', '1', 'Hutang Bank BCA', NULL, 'liability', 'general_ledger', 4, 'credit', 1, 'BALANCE_SHEET', 'LIABILITY', 'financing', 'FINANCING', 'Penerimaan/(pelunasan) hutang bank jangka panjang', NULL, NULL, NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('2-20200', '2-20200', '20200', 'Hutang Pemegang Saham', NULL, 'liability', 'sub_account', 3, 'credit', 2, 'BALANCE_SHEET', 'LIABILITY', 'financing', 'FINANCING', 'Penerimaan/(pelunasan) hutang pemegang saham', NULL, NULL, NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('2-20200-1', '2-20200-1', '1', 'Hutang Pemegang Saham', NULL, 'liability', 'general_ledger', 4, 'credit', 1, 'BALANCE_SHEET', 'LIABILITY', 'financing', 'FINANCING', 'Penerimaan/(pelunasan) hutang pemegang saham', NULL, NULL, NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('3', '3', '3', 'EKUITAS', NULL, 'equity', 'category', 1, 'credit', 3, 'BALANCE_SHEET', 'EQUITY', 'financing', 'FINANCING', NULL, NULL, NULL, NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('3-10000', '3-10000', '10000', 'Modal', NULL, 'equity', 'type', 2, 'credit', 1, 'BALANCE_SHEET', 'EQUITY', 'financing', 'FINANCING', NULL, NULL, NULL, NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('3-10001', '3-10001', '10001', 'Modal Disetor', NULL, 'equity', 'sub_account', 3, 'credit', 1, 'BALANCE_SHEET', 'EQUITY', 'financing', 'FINANCING', 'Setoran modal', NULL, NULL, NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('3-10001-1', '3-10001-1', '1', 'Modal Saham PT. WIT', NULL, 'equity', 'general_ledger', 4, 'credit', 1, 'BALANCE_SHEET', 'EQUITY', 'financing', 'FINANCING', 'Setoran modal', NULL, NULL, NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('3-20000', '3-20000', '20000', 'Saldo Laba', NULL, 'equity', 'type', 2, 'credit', 2, 'BALANCE_SHEET', 'EQUITY', 'not_applicable', 'EXCLUDED', NULL, NULL, NULL, NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('3-20001', '3-20001', '20001', 'Saldo Laba Ditahan', NULL, 'equity', 'sub_account', 3, 'credit', 1, 'BALANCE_SHEET', 'EQUITY', 'not_applicable', 'EXCLUDED', NULL, NULL, NULL, NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('3-20001-1', '3-20001-1', '1', 'Akumulasi Laba Ditahan', NULL, 'equity', 'general_ledger', 4, 'credit', 1, 'BALANCE_SHEET', 'EQUITY', 'not_applicable', 'EXCLUDED', NULL, NULL, NULL, NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('3-20002', '3-20002', '20002', 'Laba Tahun Berjalan', NULL, 'equity', 'sub_account', 3, 'credit', 2, 'BALANCE_SHEET', 'EQUITY', 'not_applicable', 'EXCLUDED', NULL, NULL, NULL, NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('3-20002-1', '3-20002-1', '1', 'Laba Bersih Periode Berjalan', NULL, 'equity', 'general_ledger', 4, 'credit', 1, 'BALANCE_SHEET', 'EQUITY', 'not_applicable', 'EXCLUDED', NULL, NULL, NULL, NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('4', '4', '4', 'PENDAPATAN', NULL, 'revenue', 'category', 1, 'credit', 10, 'INCOME_STATEMENT', 'REVENUE', 'operating', 'OPERATING', 'Penerimaan dari pelanggan', NULL, NULL, NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('4-40000', '4-40000', '40000', 'Project Based Revenue', NULL, 'revenue', 'type', 2, 'credit', 1, 'INCOME_STATEMENT', 'REVENUE', 'operating', 'OPERATING', 'Penerimaan dari pelanggan', NULL, NULL, NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('4-40000-1', '4-40000-1', '1', 'Project Based - Project Revenue', NULL, 'revenue', 'sub_account', 3, 'credit', 1, 'INCOME_STATEMENT', 'REVENUE', 'operating', 'OPERATING', 'Penerimaan dari pelanggan', NULL, NULL, NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('4-40000-2', '4-40000-2', '2', 'Project Based - MaaS Revenue', NULL, 'revenue', 'sub_account', 3, 'credit', 2, 'INCOME_STATEMENT', 'REVENUE', 'operating', 'OPERATING', 'Penerimaan dari pelanggan', NULL, NULL, NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('4-40000-3', '4-40000-3', '3', 'Project Based - WMS Revenue', NULL, 'revenue', 'sub_account', 3, 'credit', 3, 'INCOME_STATEMENT', 'REVENUE', 'operating', 'OPERATING', 'Penerimaan dari pelanggan', NULL, NULL, NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('4-40000-4', '4-40000-4', '4', 'Project Based - Procurement Revenue', NULL, 'revenue', 'sub_account', 3, 'credit', 4, 'INCOME_STATEMENT', 'REVENUE', 'operating', 'OPERATING', 'Penerimaan dari pelanggan', NULL, NULL, NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('4-40000-5', '4-40000-5', '5', 'Project Based - Website Revenue', NULL, 'revenue', 'sub_account', 3, 'credit', 5, 'INCOME_STATEMENT', 'REVENUE', 'operating', 'OPERATING', 'Penerimaan dari pelanggan', NULL, NULL, NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('4-40000-6', '4-40000-6', '6', 'Project Based - Hosting Revenue', NULL, 'revenue', 'sub_account', 3, 'credit', 6, 'INCOME_STATEMENT', 'REVENUE', 'operating', 'OPERATING', 'Penerimaan dari pelanggan', NULL, NULL, NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('4-40000-7', '4-40000-7', '7', 'Project Based - Domain Revenue', NULL, 'revenue', 'sub_account', 3, 'credit', 7, 'INCOME_STATEMENT', 'REVENUE', 'operating', 'OPERATING', 'Penerimaan dari pelanggan', NULL, NULL, NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('4-40000-8', '4-40000-8', '8', 'Project Based - Consultant Revenue', NULL, 'revenue', 'sub_account', 3, 'credit', 8, 'INCOME_STATEMENT', 'REVENUE', 'operating', 'OPERATING', 'Penerimaan dari pelanggan', NULL, NULL, NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('4-40000-9', '4-40000-9', '9', 'Project Based - Add on / Change Request', NULL, 'revenue', 'sub_account', 3, 'credit', 9, 'INCOME_STATEMENT', 'REVENUE', 'operating', 'OPERATING', 'Penerimaan dari pelanggan', NULL, NULL, NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('4-40000-99', '4-40000-99', '99', 'Project Based - Lain Lain', NULL, 'revenue', 'sub_account', 3, 'credit', 99, 'INCOME_STATEMENT', 'REVENUE', 'operating', 'OPERATING', 'Penerimaan dari pelanggan', NULL, NULL, NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('4-40100', '4-40100', '40100', 'Maintenance / Recurring Revenue', NULL, 'revenue', 'type', 2, 'credit', 2, 'INCOME_STATEMENT', 'REVENUE', 'operating', 'OPERATING', 'Penerimaan dari pelanggan', NULL, NULL, NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('4-40100-1', '4-40100-1', '1', 'MTN/R - Project Revenue', NULL, 'revenue', 'sub_account', 3, 'credit', 1, 'INCOME_STATEMENT', 'REVENUE', 'operating', 'OPERATING', 'Penerimaan dari pelanggan', NULL, NULL, NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('4-40100-2', '4-40100-2', '2', 'MTN/R - WMS Revenue', NULL, 'revenue', 'sub_account', 3, 'credit', 2, 'INCOME_STATEMENT', 'REVENUE', 'operating', 'OPERATING', 'Penerimaan dari pelanggan', NULL, NULL, NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('4-40100-3', '4-40100-3', '3', 'MTN/R - Spa Management System Revenue', NULL, 'revenue', 'sub_account', 3, 'credit', 3, 'INCOME_STATEMENT', 'REVENUE', 'operating', 'OPERATING', 'Penerimaan dari pelanggan', NULL, NULL, NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('4-40100-4', '4-40100-4', '4', 'MTN/R - Leisure & Park Mgmt System Revenue', NULL, 'revenue', 'sub_account', 3, 'credit', 4, 'INCOME_STATEMENT', 'REVENUE', 'operating', 'OPERATING', 'Penerimaan dari pelanggan', NULL, NULL, NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('4-40100-5', '4-40100-5', '5', 'MTN/R - Website Revenue', NULL, 'revenue', 'sub_account', 3, 'credit', 5, 'INCOME_STATEMENT', 'REVENUE', 'operating', 'OPERATING', 'Penerimaan dari pelanggan', NULL, NULL, NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('4-40100-6', '4-40100-6', '6', 'MTN/R - Manage Service', NULL, 'revenue', 'sub_account', 3, 'credit', 6, 'INCOME_STATEMENT', 'REVENUE', 'operating', 'OPERATING', 'Penerimaan dari pelanggan', NULL, NULL, NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('4-40700', '4-40700', '40700', 'Sales Discount', NULL, 'revenue', 'type', 2, 'credit', 3, 'INCOME_STATEMENT', 'REVENUE', 'operating', 'OPERATING', 'Penerimaan dari pelanggan', NULL, NULL, NULL, true, false, false, true, true, false, true, false, false, false, false, true),
  ('5', '5', '5', 'BEBAN POKOK PENDAPATAN', NULL, 'expense', 'category', 1, 'debit', 20, 'INCOME_STATEMENT', 'COGS', 'operating', 'OPERATING', 'Pembayaran kepada pemasok dan kontraktor', 'DIRECT', NULL, NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('5-50000', '5-50000', '50000', 'Beban Pokok Pendapatan', NULL, 'expense', 'type', 2, 'debit', 1, 'INCOME_STATEMENT', 'COGS', 'operating', 'OPERATING', 'Pembayaran kepada pemasok dan kontraktor', 'DIRECT', NULL, NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('5-50000-1', '5-50000-1', '1', 'Fee / Bonus', NULL, 'expense', 'sub_account', 3, 'debit', 1, 'INCOME_STATEMENT', 'COGS', 'operating', 'OPERATING', 'Pembayaran kepada pemasok dan kontraktor', 'DIRECT', 'PERSONNEL', NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('5-50000-1-3', '5-50000-1-3', '3', 'Fee / Bonus - Project Member', NULL, 'expense', 'general_ledger', 4, 'debit', 3, 'INCOME_STATEMENT', 'COGS', 'operating', 'OPERATING', 'Pembayaran kepada pemasok dan kontraktor', 'DIRECT', 'PERSONNEL', NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('5-50000-2', '5-50000-2', '2', '3rd Party - Vendor / Partner', NULL, 'expense', 'sub_account', 3, 'debit', 2, 'INCOME_STATEMENT', 'COGS', 'operating', 'OPERATING', 'Pembayaran kepada pemasok dan kontraktor', 'DIRECT', 'OPERATIONAL', NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('5-50000-2-10', '5-50000-2-10', '10', 'Partner - Artisun', NULL, 'expense', 'general_ledger', 4, 'debit', 10, 'INCOME_STATEMENT', 'COGS', 'operating', 'OPERATING', 'Pembayaran kepada pemasok dan kontraktor', 'DIRECT', 'OPERATIONAL', NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('5-50000-2-11', '5-50000-2-11', '11', 'Partner - WHITE', NULL, 'expense', 'general_ledger', 4, 'debit', 11, 'INCOME_STATEMENT', 'COGS', 'operating', 'OPERATING', 'Pembayaran kepada pemasok dan kontraktor', 'DIRECT', 'OPERATIONAL', NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('5-50000-2-2', '5-50000-2-2', '2', 'Partner - Plabs', NULL, 'expense', 'general_ledger', 4, 'debit', 2, 'INCOME_STATEMENT', 'COGS', 'operating', 'OPERATING', 'Pembayaran kepada pemasok dan kontraktor', 'DIRECT', 'OPERATIONAL', NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('5-50000-2-4', '5-50000-2-4', '4', 'Partner - Reza Pahlevi', NULL, 'expense', 'general_ledger', 4, 'debit', 4, 'INCOME_STATEMENT', 'COGS', 'operating', 'OPERATING', 'Pembayaran kepada pemasok dan kontraktor', 'DIRECT', 'OPERATIONAL', NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('5-50000-2-6', '5-50000-2-6', '6', 'Partner - PT. MAST', NULL, 'expense', 'general_ledger', 4, 'debit', 6, 'INCOME_STATEMENT', 'COGS', 'operating', 'OPERATING', 'Pembayaran kepada pemasok dan kontraktor', 'DIRECT', 'OPERATIONAL', NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('5-50000-2-8', '5-50000-2-8', '8', 'Partner - PT. Jaya Integrasi Nusantara (JIN)', NULL, 'expense', 'general_ledger', 4, 'debit', 8, 'INCOME_STATEMENT', 'COGS', 'operating', 'OPERATING', 'Pembayaran kepada pemasok dan kontraktor', 'DIRECT', 'OPERATIONAL', NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('5-50000-3', '5-50000-3', '3', '3rd Party - Server / Hosting', NULL, 'expense', 'sub_account', 3, 'debit', 3, 'INCOME_STATEMENT', 'COGS', 'operating', 'OPERATING', 'Pembayaran kepada pemasok dan kontraktor', 'DIRECT', 'TECHNOLOGY', NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('5-50000-3-1', '5-50000-3-1', '1', 'Server / Hosting - Niagahoster', NULL, 'expense', 'general_ledger', 4, 'debit', 1, 'INCOME_STATEMENT', 'COGS', 'operating', 'OPERATING', 'Pembayaran kepada pemasok dan kontraktor', 'DIRECT', 'TECHNOLOGY', NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('5-50000-3-10', '5-50000-3-10', '10', 'Server / Hosting - Google Cloud Platform (GCP)', NULL, 'expense', 'general_ledger', 4, 'debit', 10, 'INCOME_STATEMENT', 'COGS', 'operating', 'OPERATING', 'Pembayaran kepada pemasok dan kontraktor', 'DIRECT', 'TECHNOLOGY', NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('5-50000-3-12', '5-50000-3-12', '12', 'Server / Hosting - Jakarta Web Hosting', NULL, 'expense', 'general_ledger', 4, 'debit', 12, 'INCOME_STATEMENT', 'COGS', 'operating', 'OPERATING', 'Pembayaran kepada pemasok dan kontraktor', 'DIRECT', 'TECHNOLOGY', NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('5-50000-3-13', '5-50000-3-13', '13', 'Server / Hosting - Microsoft Azure', NULL, 'expense', 'general_ledger', 4, 'debit', 13, 'INCOME_STATEMENT', 'COGS', 'operating', 'OPERATING', 'Pembayaran kepada pemasok dan kontraktor', 'DIRECT', 'TECHNOLOGY', NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('5-50000-3-2', '5-50000-3-2', '2', 'Server / Hosting - Idcloudhost', NULL, 'expense', 'general_ledger', 4, 'debit', 2, 'INCOME_STATEMENT', 'COGS', 'operating', 'OPERATING', 'Pembayaran kepada pemasok dan kontraktor', 'DIRECT', 'TECHNOLOGY', NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('5-50000-3-4', '5-50000-3-4', '4', 'Server / Hosting - Dracoola', NULL, 'expense', 'general_ledger', 4, 'debit', 4, 'INCOME_STATEMENT', 'COGS', 'operating', 'OPERATING', 'Pembayaran kepada pemasok dan kontraktor', 'DIRECT', 'TECHNOLOGY', NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('5-50000-4', '5-50000-4', '4', 'Other COGS', NULL, 'expense', 'sub_account', 3, 'debit', 4, 'INCOME_STATEMENT', 'COGS', 'operating', 'OPERATING', 'Pembayaran kepada pemasok dan kontraktor', 'DIRECT', 'OPERATIONAL', NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('5-50000-4-1', '5-50000-4-1', '1', '3rd Party - Biaya Domain', NULL, 'expense', 'general_ledger', 4, 'debit', 1, 'INCOME_STATEMENT', 'COGS', 'operating', 'OPERATING', 'Pembayaran kepada pemasok dan kontraktor', 'DIRECT', 'TECHNOLOGY', NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('5-50000-5', '5-50000-5', '5', 'Other COGS - Miscellaneous', NULL, 'expense', 'sub_account', 3, 'debit', 5, 'INCOME_STATEMENT', 'COGS', 'operating', 'OPERATING', 'Pembayaran kepada pemasok dan kontraktor', 'DIRECT', 'OPERATIONAL', NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('5-50000-5-1', '5-50000-5-1', '1', 'Other COGS - Procurement', NULL, 'expense', 'general_ledger', 4, 'debit', 1, 'INCOME_STATEMENT', 'COGS', 'operating', 'OPERATING', 'Pembayaran kepada pemasok dan kontraktor', 'DIRECT', 'OPERATIONAL', NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('5-50000-5-3', '5-50000-5-3', '3', 'Other COGS - Plugin / Add Ons', NULL, 'expense', 'general_ledger', 4, 'debit', 3, 'INCOME_STATEMENT', 'COGS', 'operating', 'OPERATING', 'Pembayaran kepada pemasok dan kontraktor', 'DIRECT', 'TECHNOLOGY', NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('5-50000-5-4', '5-50000-5-4', '4', 'Other COGS - Lain Lain', NULL, 'expense', 'general_ledger', 4, 'debit', 4, 'INCOME_STATEMENT', 'COGS', 'operating', 'OPERATING', 'Pembayaran kepada pemasok dan kontraktor', 'DIRECT', 'OPERATIONAL', NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('5-50000-5-5', '5-50000-5-5', '5', 'Other COGS - Google Workspace / GSuite', NULL, 'expense', 'general_ledger', 4, 'debit', 5, 'INCOME_STATEMENT', 'COGS', 'operating', 'OPERATING', 'Pembayaran kepada pemasok dan kontraktor', 'DIRECT', 'TECHNOLOGY', NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('6', '6', '6', 'BEBAN OPERASIONAL', NULL, 'expense', 'category', 1, 'debit', 30, 'INCOME_STATEMENT', 'OPEX', 'operating', 'OPERATING', 'Pembayaran beban operasional', 'INDIRECT', NULL, NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('6-60100', '6-60100', '60100', 'General & Administrative Expenses', NULL, 'expense', 'type', 2, 'debit', 1, 'INCOME_STATEMENT', 'OPEX', 'operating', 'OPERATING', 'Pembayaran gaji dan beban umum administrasi', 'INDIRECT', NULL, NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('6-60100-1', '6-60100-1', '1', 'Gaji Pokok (Payroll/Salary)', NULL, 'expense', 'sub_account', 3, 'debit', 1, 'INCOME_STATEMENT', 'OPEX', 'operating', 'OPERATING', 'Pembayaran gaji dan beban umum administrasi', 'INDIRECT', 'PERSONNEL', NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('6-60100-10', '6-60100-10', '10', 'BPJS', NULL, 'expense', 'sub_account', 3, 'debit', 10, 'INCOME_STATEMENT', 'OPEX', 'operating', 'OPERATING', 'Pembayaran gaji dan beban umum administrasi', 'INDIRECT', 'PERSONNEL', NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('6-60100-11', '6-60100-11', '11', 'Electricity', NULL, 'expense', 'sub_account', 3, 'debit', 11, 'INCOME_STATEMENT', 'OPEX', 'operating', 'OPERATING', 'Pembayaran gaji dan beban umum administrasi', 'INDIRECT', 'OPERATIONAL', NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('6-60100-12', '6-60100-12', '12', 'Phone', NULL, 'expense', 'sub_account', 3, 'debit', 12, 'INCOME_STATEMENT', 'OPEX', 'operating', 'OPERATING', 'Pembayaran gaji dan beban umum administrasi', 'INDIRECT', 'OPERATIONAL', NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('6-60100-13', '6-60100-13', '13', 'Biznet Sukakarya', NULL, 'expense', 'sub_account', 3, 'debit', 13, 'INCOME_STATEMENT', 'OPEX', 'operating', 'OPERATING', 'Pembayaran gaji dan beban umum administrasi', 'INDIRECT', 'OPERATIONAL', NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('6-60100-15', '6-60100-15', '15', 'Cleanliness / Kebersihan', NULL, 'expense', 'sub_account', 3, 'debit', 15, 'INCOME_STATEMENT', 'OPEX', 'operating', 'OPERATING', 'Pembayaran gaji dan beban umum administrasi', 'INDIRECT', 'OVERHEAD', NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('6-60100-16', '6-60100-16', '16', 'Parking', NULL, 'expense', 'sub_account', 3, 'debit', 16, 'INCOME_STATEMENT', 'OPEX', 'operating', 'OPERATING', 'Pembayaran gaji dan beban umum administrasi', 'INDIRECT', 'OVERHEAD', NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('6-60100-17', '6-60100-17', '17', 'Cicilan Rent Office / Kontrakan', NULL, 'expense', 'sub_account', 3, 'debit', 17, 'INCOME_STATEMENT', 'OPEX', 'operating', 'OPERATING', 'Pembayaran gaji dan beban umum administrasi', 'INDIRECT', 'OPERATIONAL', NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('6-60100-18', '6-60100-18', '18', 'Marketing Fee External - Nix', NULL, 'expense', 'sub_account', 3, 'debit', 18, 'INCOME_STATEMENT', 'OPEX', 'operating', 'OPERATING', 'Pembayaran gaji dan beban umum administrasi', 'INDIRECT', 'MARKETING', NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('6-60100-19', '6-60100-19', '19', 'Olahraga', NULL, 'expense', 'sub_account', 3, 'debit', 19, 'INCOME_STATEMENT', 'OPEX', 'operating', 'OPERATING', 'Pembayaran gaji dan beban umum administrasi', 'INDIRECT', 'OVERHEAD', NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('6-60100-2', '6-60100-2', '2', 'Tunjangan Hari Raya (THR)', NULL, 'expense', 'sub_account', 3, 'debit', 2, 'INCOME_STATEMENT', 'OPEX', 'operating', 'OPERATING', 'Pembayaran gaji dan beban umum administrasi', 'INDIRECT', 'PERSONNEL', NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('6-60100-20', '6-60100-20', '20', 'Surat Perintah Perjalanan Dinas', NULL, 'expense', 'sub_account', 3, 'debit', 20, 'INCOME_STATEMENT', 'OPEX', 'operating', 'OPERATING', 'Pembayaran gaji dan beban umum administrasi', 'INDIRECT', 'OPERATIONAL', NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('6-60100-21', '6-60100-21', '21', 'Biaya Entertainment', NULL, 'expense', 'sub_account', 3, 'debit', 21, 'INCOME_STATEMENT', 'OPEX', 'operating', 'OPERATING', 'Pembayaran gaji dan beban umum administrasi', 'INDIRECT', 'OVERHEAD', NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('6-60100-23', '6-60100-23', '23', 'Biaya Inventaris Kantor', NULL, 'expense', 'sub_account', 3, 'debit', 23, 'INCOME_STATEMENT', 'OPEX', 'operating', 'OPERATING', 'Pembayaran gaji dan beban umum administrasi', 'INDIRECT', 'OVERHEAD', NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('6-60100-4', '6-60100-4', '4', 'Marketing Expenses', NULL, 'expense', 'sub_account', 3, 'debit', 4, 'INCOME_STATEMENT', 'OPEX', 'operating', 'OPERATING', 'Pembayaran gaji dan beban umum administrasi', 'INDIRECT', 'MARKETING', NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('6-60100-6', '6-60100-6', '6', 'Asisten Rumah Tangga (ART)', NULL, 'expense', 'sub_account', 3, 'debit', 6, 'INCOME_STATEMENT', 'OPEX', 'operating', 'OPERATING', 'Pembayaran gaji dan beban umum administrasi', 'INDIRECT', 'OVERHEAD', NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('6-60100-7', '6-60100-7', '7', 'Security', NULL, 'expense', 'sub_account', 3, 'debit', 7, 'INCOME_STATEMENT', 'OPEX', 'operating', 'OPERATING', 'Pembayaran gaji dan beban umum administrasi', 'INDIRECT', 'OVERHEAD', NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('6-60100-8', '6-60100-8', '8', 'Infaq', NULL, 'expense', 'sub_account', 3, 'debit', 8, 'INCOME_STATEMENT', 'OPEX', 'operating', 'OPERATING', 'Pembayaran gaji dan beban umum administrasi', 'INDIRECT', 'OVERHEAD', NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('6-60100-9', '6-60100-9', '9', 'Insurance', NULL, 'expense', 'sub_account', 3, 'debit', 9, 'INCOME_STATEMENT', 'OPEX', 'operating', 'OPERATING', 'Pembayaran gaji dan beban umum administrasi', 'INDIRECT', 'PERSONNEL', NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('6-60100-99', '6-60100-99', '99', 'Biaya Lain-lain', NULL, 'expense', 'sub_account', 3, 'debit', 99, 'INCOME_STATEMENT', 'OPEX', 'operating', 'OPERATING', 'Pembayaran gaji dan beban umum administrasi', 'INDIRECT', 'OVERHEAD', NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('6-60200', '6-60200', '60200', '3rd Party Expenses', NULL, 'expense', 'type', 2, 'debit', 2, 'INCOME_STATEMENT', 'OPEX', 'operating', 'OPERATING', 'Pembayaran pihak ketiga', 'INDIRECT', NULL, NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('6-60200-1', '6-60200-1', '1', '3rd Party - BBF Agensi Pajak', NULL, 'expense', 'sub_account', 3, 'debit', 1, 'INCOME_STATEMENT', 'OPEX', 'operating', 'OPERATING', 'Pembayaran pihak ketiga', 'INDIRECT', 'OVERHEAD', NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('6-60200-2', '6-60200-2', '2', '3rd Party - Postman', NULL, 'expense', 'sub_account', 3, 'debit', 2, 'INCOME_STATEMENT', 'OPEX', 'operating', 'OPERATING', 'Pembayaran pihak ketiga', 'INDIRECT', 'TECHNOLOGY', NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('6-60200-3', '6-60200-3', '3', '3rd Party - Figma', NULL, 'expense', 'sub_account', 3, 'debit', 3, 'INCOME_STATEMENT', 'OPEX', 'operating', 'OPERATING', 'Pembayaran pihak ketiga', 'INDIRECT', 'TECHNOLOGY', NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('6-60200-4', '6-60200-4', '4', '3rd Party - Google Workspace (Internal WIT.ID)', NULL, 'expense', 'sub_account', 3, 'debit', 4, 'INCOME_STATEMENT', 'OPEX', 'operating', 'OPERATING', 'Pembayaran pihak ketiga', 'INDIRECT', 'TECHNOLOGY', NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('6-60200-99', '6-60200-99', '99', '3rd Party Expenses - Lain Lain', NULL, 'expense', 'sub_account', 3, 'debit', 99, 'INCOME_STATEMENT', 'OPEX', 'operating', 'OPERATING', 'Pembayaran pihak ketiga', 'INDIRECT', 'TECHNOLOGY', NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('6-60221', '6-60221', '60221', 'Beban Pajak', NULL, 'expense', 'type', 2, 'debit', 5, 'INCOME_STATEMENT', 'TAX_EXPENSE', 'operating', 'OPERATING', 'Pembayaran pajak penghasilan dan PPN', 'INDIRECT', NULL, NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('6-60222', '6-60222', '60222', 'Beban Pajak - PPh 21', NULL, 'expense', 'sub_account', 3, 'debit', 1, 'INCOME_STATEMENT', 'TAX_EXPENSE', 'operating', 'OPERATING', 'Pembayaran pajak penghasilan dan PPN', 'INDIRECT', 'PERSONNEL', NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('6-60223', '6-60223', '60223', 'Beban Pajak - PPh 23', NULL, 'expense', 'sub_account', 3, 'debit', 2, 'INCOME_STATEMENT', 'TAX_EXPENSE', 'operating', 'OPERATING', 'Pembayaran pajak penghasilan dan PPN', 'INDIRECT', 'OVERHEAD', NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('6-60224', '6-60224', '60224', 'Beban Pajak - PPh 4(2)', NULL, 'expense', 'sub_account', 3, 'debit', 3, 'INCOME_STATEMENT', 'TAX_EXPENSE', 'operating', 'OPERATING', 'Pembayaran pajak penghasilan dan PPN', 'INDIRECT', 'OVERHEAD', NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('6-60225', '6-60225', '60225', 'Beban Pajak - PPN', NULL, 'expense', 'sub_account', 3, 'debit', 4, 'INCOME_STATEMENT', 'TAX_EXPENSE', 'operating', 'OPERATING', 'Pembayaran pajak penghasilan dan PPN', 'INDIRECT', 'OVERHEAD', NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('6-60226', '6-60226', '60226', 'Beban Pajak - PPh 25', NULL, 'expense', 'sub_account', 3, 'debit', 5, 'INCOME_STATEMENT', 'TAX_EXPENSE', 'operating', 'OPERATING', 'Pembayaran pajak penghasilan dan PPN', 'INDIRECT', 'OVERHEAD', NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('6-60300', '6-60300', '60300', 'Fee / Bonus', NULL, 'expense', 'type', 2, 'debit', 3, 'INCOME_STATEMENT', 'OPEX', 'operating', 'OPERATING', 'Pembayaran fee dan bonus', 'INDIRECT', NULL, NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('6-60300-1', '6-60300-1', '1', 'Fee / Bonus - Marketing Fee External', NULL, 'expense', 'sub_account', 3, 'debit', 1, 'INCOME_STATEMENT', 'OPEX', 'operating', 'OPERATING', 'Pembayaran fee dan bonus', 'INDIRECT', 'MARKETING', NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('6-60300-2', '6-60300-2', '2', 'Fee / Bonus - Marketing Internal', NULL, 'expense', 'sub_account', 3, 'debit', 2, 'INCOME_STATEMENT', 'OPEX', 'operating', 'OPERATING', 'Pembayaran fee dan bonus', 'INDIRECT', 'MARKETING', NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('6-60300-5', '6-60300-5', '5', 'Fee / Bonus - Management Fee', NULL, 'expense', 'sub_account', 3, 'debit', 5, 'INCOME_STATEMENT', 'OPEX', 'operating', 'OPERATING', 'Pembayaran fee dan bonus', 'INDIRECT', 'OVERHEAD', NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('6-60400', '6-60400', '60400', 'Depresiasi & Amortisasi', NULL, 'expense', 'type', 2, 'debit', 4, 'INCOME_STATEMENT', 'OPEX', 'non_cash', 'OPERATING', 'Penyusutan dan amortisasi', 'INDIRECT', NULL, NULL, false, false, false, true, true, false, true, false, false, false, false, true),
  ('6-60400-1', '6-60400-1', '1', 'Depresiasi Aset Tetap', NULL, 'expense', 'sub_account', 3, 'debit', 1, 'INCOME_STATEMENT', 'OPEX', 'non_cash', 'OPERATING', 'Penyusutan aset tetap', 'INDIRECT', 'OVERHEAD', NULL, false, false, true, true, true, false, true, false, false, false, false, true),
  ('6-60400-2', '6-60400-2', '2', 'Amortisasi Aset Tak Berwujud', NULL, 'expense', 'sub_account', 3, 'debit', 2, 'INCOME_STATEMENT', 'OPEX', 'non_cash', 'OPERATING', 'Amortisasi aset tak berwujud', 'INDIRECT', 'OVERHEAD', NULL, false, false, true, true, true, false, true, false, false, false, false, true),
  ('7', '7', '7', 'PENDAPATAN LAIN-LAIN', NULL, 'revenue', 'category', 1, 'credit', 40, 'INCOME_STATEMENT', 'OTHER_INCOME', 'operating', 'OPERATING', 'Penerimaan pendapatan lain-lain', NULL, NULL, NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('7-70000', '7-70000', '70000', 'Interest Income - Bank', NULL, 'revenue', 'type', 2, 'credit', 1, 'INCOME_STATEMENT', 'OTHER_INCOME', 'operating', 'OPERATING', 'Penerimaan pendapatan lain-lain', NULL, NULL, NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('7-70099', '7-70099', '70099', 'Pendapatan Non Operasional - Lain-Lain', NULL, 'revenue', 'type', 2, 'credit', 2, 'INCOME_STATEMENT', 'OTHER_INCOME', 'operating', 'OPERATING', 'Penerimaan pendapatan lain-lain', NULL, NULL, NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('8', '8', '8', 'BEBAN LAIN-LAIN', NULL, 'expense', 'category', 1, 'debit', 50, 'INCOME_STATEMENT', 'OTHER_EXPENSE', 'operating', 'OPERATING', 'Pembayaran beban non-operasional', NULL, NULL, NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('8-80000', '8-80000', '80000', 'Beban Non Operasional', NULL, 'expense', 'type', 2, 'debit', 1, 'INCOME_STATEMENT', 'OTHER_EXPENSE', 'operating', 'OPERATING', 'Pembayaran beban non-operasional', NULL, NULL, NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('8-80003', '8-80003', '80003', 'Bank Taxes', NULL, 'expense', 'sub_account', 3, 'debit', 1, 'INCOME_STATEMENT', 'OTHER_EXPENSE', 'operating', 'OPERATING', 'Pembayaran beban non-operasional', NULL, 'OVERHEAD', NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('8-80006', '8-80006', '80006', 'Employee Loan', NULL, 'expense', 'sub_account', 3, 'debit', 2, 'INCOME_STATEMENT', 'OTHER_EXPENSE', 'operating', 'OPERATING', 'Pembayaran beban non-operasional', NULL, 'OVERHEAD', NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('8-80007', '8-80007', '80007', 'Office Renovation', NULL, 'expense', 'sub_account', 3, 'debit', 3, 'INCOME_STATEMENT', 'OTHER_EXPENSE', 'operating', 'OPERATING', 'Pembayaran beban non-operasional', NULL, 'OVERHEAD', NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('8-80009', '8-80009', '80009', 'Bank Administration', NULL, 'expense', 'sub_account', 3, 'debit', 4, 'INCOME_STATEMENT', 'OTHER_EXPENSE', 'operating', 'OPERATING', 'Pembayaran beban non-operasional', NULL, 'OVERHEAD', NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('8-80010', '8-80010', '80010', 'WWW Coffee', NULL, 'expense', 'sub_account', 3, 'debit', 5, 'INCOME_STATEMENT', 'OTHER_EXPENSE', 'operating', 'OPERATING', 'Pembayaran beban non-operasional', NULL, 'OVERHEAD', NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('8-80012', '8-80012', '80012', 'Ultah WIT.ID', NULL, 'expense', 'sub_account', 3, 'debit', 6, 'INCOME_STATEMENT', 'OTHER_EXPENSE', 'operating', 'OPERATING', 'Pembayaran beban non-operasional', NULL, 'OVERHEAD', NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('8-80013', '8-80013', '80013', 'Hampers WIT.ID', NULL, 'expense', 'sub_account', 3, 'debit', 7, 'INCOME_STATEMENT', 'OTHER_EXPENSE', 'operating', 'OPERATING', 'Pembayaran beban non-operasional', NULL, 'OVERHEAD', NULL, false, false, false, false, true, false, true, false, false, false, false, true),
  ('8-80014', '8-80014', '80014', 'Buka Bersama', NULL, 'expense', 'sub_account', 3, 'debit', 8, 'INCOME_STATEMENT', 'OTHER_EXPENSE', 'operating', 'OPERATING', 'Pembayaran beban non-operasional', NULL, 'OVERHEAD', NULL, false, false, false, false, true, false, true, false, false, false, false, true)
) AS t(
  account_code, coa_full_code, segment_code, account_name, name_en,
  account_type, coa_layer, level, normal_balance, sort_order,
  enum_laporan_keuangan, enum_laporan_keuangan_category,
  cash_flow_category, enum_cf_section, enum_cf_line,
  direct_indirect_cost, enum_cost_category, tax_code,
  contra_account, is_working_capital, is_non_cash_item, is_budgeted,
  is_tax_deductible, is_restricted, is_trial_balance, is_taxation_report,
  required_sub_gl, is_washed_out_account, required_child, is_active
);

-- == Pass 2: wire parent_account_id by code (ADR-8) ==========================
WITH pairs(child_code, parent_code) AS (VALUES
  ('1-10000', '1'),
  ('1-10001', '1-10000'),
  ('1-10001-1', '1-10001'),
  ('1-10002', '1-10000'),
  ('1-10002-1', '1-10002'),
  ('1-10002-2', '1-10002'),
  ('1-10002-3', '1-10002'),
  ('1-10002-4', '1-10002'),
  ('1-10002-5', '1-10002'),
  ('1-10002-6', '1-10002'),
  ('1-10003', '1-10000'),
  ('1-10003-1', '1-10003'),
  ('1-10100', '1-10000'),
  ('1-10100-1', '1-10100'),
  ('1-10100-2', '1-10100'),
  ('1-10100-9', '1-10100'),
  ('1-10200', '1-10000'),
  ('1-10200-1', '1-10200'),
  ('1-10200-9', '1-10200'),
  ('1-10300', '1-10000'),
  ('1-10300-1', '1-10300'),
  ('1-10300-2', '1-10300'),
  ('1-10400', '1-10000'),
  ('1-10400-1', '1-10400'),
  ('1-10400-2', '1-10400'),
  ('1-10400-3', '1-10400'),
  ('1-20000', '1'),
  ('1-20001', '1-20000'),
  ('1-20001-1', '1-20001'),
  ('1-20001-2', '1-20001'),
  ('1-20001-3', '1-20001'),
  ('1-20001-9', '1-20001'),
  ('1-20002', '1-20000'),
  ('1-20002-1', '1-20002'),
  ('1-20002-9', '1-20002'),
  ('1-20003', '1-20000'),
  ('1-20003-1', '1-20003'),
  ('1-20003-2', '1-20003'),
  ('2-10000', '2'),
  ('2-10100', '2-10000'),
  ('2-10100-1', '2-10100'),
  ('2-10100-2', '2-10100'),
  ('2-10200', '2-10000'),
  ('2-10200-1', '2-10200'),
  ('2-10200-2', '2-10200'),
  ('2-10200-3', '2-10200'),
  ('2-10200-4', '2-10200'),
  ('2-10200-5', '2-10200'),
  ('2-10300', '2-10000'),
  ('2-10300-1', '2-10300'),
  ('2-10300-2', '2-10300'),
  ('2-10400', '2-10000'),
  ('2-10400-1', '2-10400'),
  ('2-10500', '2-10000'),
  ('2-10500-1', '2-10500'),
  ('2-20000', '2'),
  ('2-20100', '2-20000'),
  ('2-20100-1', '2-20100'),
  ('2-20200', '2-20000'),
  ('2-20200-1', '2-20200'),
  ('3-10000', '3'),
  ('3-10001', '3-10000'),
  ('3-10001-1', '3-10001'),
  ('3-20000', '3'),
  ('3-20001', '3-20000'),
  ('3-20001-1', '3-20001'),
  ('3-20002', '3-20000'),
  ('3-20002-1', '3-20002'),
  ('4-40000', '4'),
  ('4-40000-1', '4-40000'),
  ('4-40000-2', '4-40000'),
  ('4-40000-3', '4-40000'),
  ('4-40000-4', '4-40000'),
  ('4-40000-5', '4-40000'),
  ('4-40000-6', '4-40000'),
  ('4-40000-7', '4-40000'),
  ('4-40000-8', '4-40000'),
  ('4-40000-9', '4-40000'),
  ('4-40000-99', '4-40000'),
  ('4-40100', '4'),
  ('4-40100-1', '4-40100'),
  ('4-40100-2', '4-40100'),
  ('4-40100-3', '4-40100'),
  ('4-40100-4', '4-40100'),
  ('4-40100-5', '4-40100'),
  ('4-40100-6', '4-40100'),
  ('4-40700', '4'),
  ('5-50000', '5'),
  ('5-50000-1', '5-50000'),
  ('5-50000-1-3', '5-50000-1'),
  ('5-50000-2', '5-50000'),
  ('5-50000-2-10', '5-50000-2'),
  ('5-50000-2-11', '5-50000-2'),
  ('5-50000-2-2', '5-50000-2'),
  ('5-50000-2-4', '5-50000-2'),
  ('5-50000-2-6', '5-50000-2'),
  ('5-50000-2-8', '5-50000-2'),
  ('5-50000-3', '5-50000'),
  ('5-50000-3-1', '5-50000-3'),
  ('5-50000-3-10', '5-50000-3'),
  ('5-50000-3-12', '5-50000-3'),
  ('5-50000-3-13', '5-50000-3'),
  ('5-50000-3-2', '5-50000-3'),
  ('5-50000-3-4', '5-50000-3'),
  ('5-50000-4', '5-50000'),
  ('5-50000-4-1', '5-50000-4'),
  ('5-50000-5', '5-50000'),
  ('5-50000-5-1', '5-50000-5'),
  ('5-50000-5-3', '5-50000-5'),
  ('5-50000-5-4', '5-50000-5'),
  ('5-50000-5-5', '5-50000-5'),
  ('6-60100', '6'),
  ('6-60100-1', '6-60100'),
  ('6-60100-10', '6-60100'),
  ('6-60100-11', '6-60100'),
  ('6-60100-12', '6-60100'),
  ('6-60100-13', '6-60100'),
  ('6-60100-15', '6-60100'),
  ('6-60100-16', '6-60100'),
  ('6-60100-17', '6-60100'),
  ('6-60100-18', '6-60100'),
  ('6-60100-19', '6-60100'),
  ('6-60100-2', '6-60100'),
  ('6-60100-20', '6-60100'),
  ('6-60100-21', '6-60100'),
  ('6-60100-23', '6-60100'),
  ('6-60100-4', '6-60100'),
  ('6-60100-6', '6-60100'),
  ('6-60100-7', '6-60100'),
  ('6-60100-8', '6-60100'),
  ('6-60100-9', '6-60100'),
  ('6-60100-99', '6-60100'),
  ('6-60200', '6'),
  ('6-60200-1', '6-60200'),
  ('6-60200-2', '6-60200'),
  ('6-60200-3', '6-60200'),
  ('6-60200-4', '6-60200'),
  ('6-60200-99', '6-60200'),
  ('6-60221', '6'),
  ('6-60222', '6-60221'),
  ('6-60223', '6-60221'),
  ('6-60224', '6-60221'),
  ('6-60225', '6-60221'),
  ('6-60226', '6-60221'),
  ('6-60300', '6'),
  ('6-60300-1', '6-60300'),
  ('6-60300-2', '6-60300'),
  ('6-60300-5', '6-60300'),
  ('6-60400', '6'),
  ('6-60400-1', '6-60400'),
  ('6-60400-2', '6-60400'),
  ('7-70000', '7'),
  ('7-70099', '7'),
  ('8-80000', '8'),
  ('8-80003', '8-80000'),
  ('8-80006', '8-80000'),
  ('8-80007', '8-80000'),
  ('8-80009', '8-80000'),
  ('8-80010', '8-80000'),
  ('8-80012', '8-80000'),
  ('8-80013', '8-80000'),
  ('8-80014', '8-80000')
)
UPDATE public.coa c
SET parent_account_id = p.id
FROM pairs, public.coa p
WHERE c.tenant_id = '00000000-0000-0000-0000-000000000001'
  AND p.tenant_id = '00000000-0000-0000-0000-000000000001'
  AND c.account_code = pairs.child_code
  AND p.account_code = pairs.parent_code;

COMMIT;
